/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as publicLayoutRouteImport } from './routes/(public)/_layout'
import { Route as protectedLayoutRouteImport } from './routes/(protected)/_layout'
import { Route as publicLayoutLoginRouteImport } from './routes/(public)/_layout/login'
import { Route as protectedLayoutServiceLayoutRouteImport } from './routes/(protected)/_layout/service/_layout'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const publicLayoutRoute = publicLayoutRouteImport.update({
  id: '/(public)/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const protectedLayoutRoute = protectedLayoutRouteImport.update({
  id: '/(protected)/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const publicLayoutLoginRoute = publicLayoutLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => publicLayoutRoute,
} as any)
const protectedLayoutServiceLayoutRoute =
  protectedLayoutServiceLayoutRouteImport.update({
    id: '/service/_layout',
    path: '/service',
    getParentRoute: () => protectedLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof publicLayoutLoginRoute
  '/service': typeof protectedLayoutServiceLayoutRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof publicLayoutLoginRoute
  '/service': typeof protectedLayoutServiceLayoutRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(protected)/_layout': typeof protectedLayoutRouteWithChildren
  '/(public)/_layout': typeof publicLayoutRouteWithChildren
  '/(public)/_layout/login': typeof publicLayoutLoginRoute
  '/(protected)/_layout/service/_layout': typeof protectedLayoutServiceLayoutRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login' | '/service'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/service'
  id:
    | '__root__'
    | '/'
    | '/(protected)/_layout'
    | '/(public)/_layout'
    | '/(public)/_layout/login'
    | '/(protected)/_layout/service/_layout'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  protectedLayoutRoute: typeof protectedLayoutRouteWithChildren
  publicLayoutRoute: typeof publicLayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/_layout': {
      id: '/(public)/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof publicLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(protected)/_layout': {
      id: '/(protected)/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof protectedLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/_layout/login': {
      id: '/(public)/_layout/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof publicLayoutLoginRouteImport
      parentRoute: typeof publicLayoutRoute
    }
    '/(protected)/_layout/service/_layout': {
      id: '/(protected)/_layout/service/_layout'
      path: '/service'
      fullPath: '/service'
      preLoaderRoute: typeof protectedLayoutServiceLayoutRouteImport
      parentRoute: typeof protectedLayoutRoute
    }
  }
}

interface protectedLayoutRouteChildren {
  protectedLayoutServiceLayoutRoute: typeof protectedLayoutServiceLayoutRoute
}

const protectedLayoutRouteChildren: protectedLayoutRouteChildren = {
  protectedLayoutServiceLayoutRoute: protectedLayoutServiceLayoutRoute,
}

const protectedLayoutRouteWithChildren = protectedLayoutRoute._addFileChildren(
  protectedLayoutRouteChildren,
)

interface publicLayoutRouteChildren {
  publicLayoutLoginRoute: typeof publicLayoutLoginRoute
}

const publicLayoutRouteChildren: publicLayoutRouteChildren = {
  publicLayoutLoginRoute: publicLayoutLoginRoute,
}

const publicLayoutRouteWithChildren = publicLayoutRoute._addFileChildren(
  publicLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  protectedLayoutRoute: protectedLayoutRouteWithChildren,
  publicLayoutRoute: publicLayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
